language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

# command to install dependencies
install: "pip install -r requirements.generic --use-mirrors"
# command to run tests
script: nosetests -v
